# Generated by Django 2.2.14 on 2020-10-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
